# Generated by Django 4.1.7 on 2023-03-27 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles_DePresse',
            fields=[
                ('Id_Articles', models.AutoField(primary_key=True, serialize=False)),
                ('Libelle_AP', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=50)),
                ('Auteur', models.CharField(max_length=50)),
                ('Date_publication', models.DateField()),
                ('Date_Syndication', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('Id_Mailing', models.AutoField(primary_key=True, serialize=False)),
                ('Notification', models.CharField(max_length=50)),
                ('Date_Envoi', models.DateField()),
                ('Destinataires', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mes_Articles',
            fields=[
                ('Id_Mes_Articles', models.AutoField(primary_key=True, serialize=False)),
                ('Libelle_MA', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=50)),
                ('Date_publication', models.DateField()),
                ('Date_Miseajour', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateurs',
            fields=[
                ('Id_Utilisateurs', models.AutoField(primary_key=True, serialize=False)),
                ('utilisateur', models.CharField(max_length=50)),
                ('mdp', models.CharField(max_length=50)),
                ('date_souscription', models.DateField()),
                ('mailng', models.BooleanField()),
                ('Id_Mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projets.mailing')),
            ],
        ),
        migrations.CreateModel(
            name='Simulations',
            fields=[
                ('Id_Simulations', models.AutoField(primary_key=True, serialize=False)),
                ('exercice', models.CharField(max_length=500)),
                ('Date_Sim', models.DateField()),
                ('graph', models.TextField()),
                ('Id_Utilisateurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projets.utilisateurs')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluations',
            fields=[
                ('Id_Evaluations', models.AutoField(primary_key=True, serialize=False)),
                ('Date_Com', models.DateField()),
                ('commentaires', models.CharField(max_length=50)),
                ('Note', models.CharField(max_length=50)),
                ('Id_Utilisateurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projets.utilisateurs')),
            ],
        ),
    ]
