# Generated by Django 4.1.7 on 2023-03-27 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles_DePresse',
            new_name='ArticlesDePresse',
        ),
        migrations.RenameModel(
            old_name='Mes_Articles',
            new_name='MesArticles',
        ),
    ]
